<?php

namespace App\Enums\Audit;

enum AuditAction: string
{
    case TenantCreated = 'tenant.created';
    case TenantActivated = 'tenant.activated';
    case TenantSuspended = 'tenant.suspended';
    case TenantReactivated = 'tenant.reactivated';
    case TenantArchived = 'tenant.archived';
    case TenantRestored = 'tenant.restored';
    case TenantDeleteAttempted = 'tenant.delete_attempted';
    case TenantDeleted = 'tenant.deleted';
    case TenantUpdated = 'tenant.updated';
    case UserEmailReleased = 'user.email_released';
    case MembershipCreated = 'membership.created';
    case MembershipRoleChanged = 'membership.role_changed';
    case MembershipStatusChanged = 'membership.status_changed';
    case MembershipRemoved = 'membership.removed';
    case WidgetKeyCreated = 'widget_key.created';
    case WidgetKeyRotated = 'widget_key.rotated';
    case WidgetKeyRevoked = 'widget_key.revoked';
    case TenantDomainCreated = 'tenant_domain.created';
    case TenantDomainVerified = 'tenant_domain.verified';
    case TenantDomainRemoved = 'tenant_domain.removed';
    case ConfigurationUpdated = 'configuration.updated';
    case BrandingUpdated = 'branding.updated';
    case LogoUpdated = 'logo.updated';
    case LogoRemoved = 'logo.removed';
    case LauncherCardUpdated = 'launcher_card.updated';
    case LauncherCardImageUpdated = 'launcher_card.image_updated';
    case LauncherCardImageRemoved = 'launcher_card.image_removed';
    case OfficeHoursUpdated = 'office_hours.updated';
    case ServiceCreated = 'service.created';
    case ServiceUpdated = 'service.updated';
    case ServiceActivated = 'service.activated';
    case ServiceDeactivated = 'service.deactivated';
    case ServiceRemoved = 'service.removed';
    case CourseCreated = 'course.created';
    case CourseUpdated = 'course.updated';
    case CourseActivated = 'course.activated';
    case CourseDeactivated = 'course.deactivated';
    case CourseRemoved = 'course.removed';
    case InstitutionCreated = 'institution.created';
    case InstitutionUpdated = 'institution.updated';
    case InstitutionActivated = 'institution.activated';
    case InstitutionDeactivated = 'institution.deactivated';
    case InstitutionRemoved = 'institution.removed';
    case LocationCreated = 'location.created';
    case LocationUpdated = 'location.updated';
    case LocationActivated = 'location.activated';
    case LocationDeactivated = 'location.deactivated';
    case LocationRemoved = 'location.removed';
    case KnowledgeCreated = 'knowledge.created';
    case KnowledgeUpdated = 'knowledge.updated';
    case KnowledgePublished = 'knowledge.published';
    case KnowledgeVersionCreated = 'knowledge.version_created';
    case KnowledgeArchived = 'knowledge.archived';
    case KnowledgeDeleted = 'knowledge.deleted';
    case KnowledgeSourceUploaded = 'knowledge.source_uploaded';
    case KnowledgeSourceRemoved = 'knowledge.source_removed';
    case FeeCreated = 'fee.created';
    case FeeUpdated = 'fee.updated';
    case FeeArchived = 'fee.archived';
    case EligibilityCreated = 'eligibility.created';
    case EligibilityUpdated = 'eligibility.updated';
    case EligibilityArchived = 'eligibility.archived';
    case CourseInstitutionCreated = 'course_institution.created';
    case CourseInstitutionUpdated = 'course_institution.updated';
    case AiConfigurationUpdated = 'ai.configuration_updated';
    case AiSecretReplaced = 'ai.secret_replaced';
    case PlatformSettingsUpdated = 'platform.settings_updated';
    case PlatformBypass = 'platform.bypass';
    case LeadCreated = 'lead.created';
    case LeadAssigned = 'lead.assigned';
    case LeadReassigned = 'lead.reassigned';
    case LeadStageChanged = 'lead.stage_changed';
    case LeadQualificationChanged = 'lead.qualification_changed';
    case LeadPriorityChanged = 'lead.priority_changed';
    case LeadFollowUpCreated = 'lead.follow_up_created';
    case LeadMarkedLost = 'lead.marked_lost';
    case LeadMarkedInvalid = 'lead.marked_invalid';
    case LeadConverted = 'lead.converted';
    case LeadReopened = 'lead.reopened';
    case LeadDeleted = 'lead.deleted';
    case LeadRestored = 'lead.restored';
    case LeadAdminOverride = 'lead.admin_override';
    case CounsellorCreated = 'counsellor.created';
    case CounsellorUpdated = 'counsellor.updated';
    case CounsellorActivated = 'counsellor.activated';
    case CounsellorDeactivated = 'counsellor.deactivated';
    case LeadQualificationRulesUpdated = 'lead.qualification_rules_updated';
    case ConversationHandoffRequested = 'conversation.handoff_requested';
    case ConversationReassigned = 'conversation.reassigned';
    case ConversationClosed = 'conversation.closed';
    case ConversationReopened = 'conversation.reopened';
    case ConversationAiResumed = 'conversation.ai_resumed';
    case PlanCreated = 'plan.created';
    case PlanUpdated = 'plan.updated';
    case PlanActivated = 'plan.activated';
    case PlanDeactivated = 'plan.deactivated';
    case SubscriptionAssigned = 'subscription.assigned';
    case SubscriptionTrialStarted = 'subscription.trial_started';
    case SubscriptionTrialExtended = 'subscription.trial_extended';
    case SubscriptionActivated = 'subscription.activated';
    case SubscriptionGraceApplied = 'subscription.grace_applied';
    case SubscriptionPastDue = 'subscription.past_due';
    case SubscriptionExpired = 'subscription.expired';
    case SubscriptionCancelScheduled = 'subscription.cancel_scheduled';
    case SubscriptionCancelled = 'subscription.cancelled';
    case SubscriptionRestored = 'subscription.restored';
    case SubscriptionPlanChanged = 'subscription.plan_changed';
    case PlanChangeRequested = 'plan_change.requested';
    case PlanChangeApproved = 'plan_change.approved';
    case PlanChangeRejected = 'plan_change.rejected';
    case EntitlementOverrideApplied = 'entitlement.override_applied';
    case EntitlementOverrideRemoved = 'entitlement.override_removed';
    case PlanPricingUpdated = 'plan.pricing_updated';
    case PaymentSecretReplaced = 'payment.secret_replaced';
    case PaymentSettingsUpdated = 'payment.settings_updated';
    case MessagingCredentialReplaced = 'messaging.credential_replaced';
    case MessagingIntegrationConfigured = 'messaging.integration_configured';
    case MessagingIntegrationEnabled = 'messaging.integration_enabled';
    case MessagingIntegrationDisabled = 'messaging.integration_disabled';

    public function label(): string
    {
        return match ($this) {
            self::TenantCreated => 'Tenant created',
            self::TenantActivated => 'Tenant activated',
            self::TenantSuspended => 'Tenant suspended',
            self::TenantReactivated => 'Tenant reactivated',
            self::TenantArchived => 'Tenant archived',
            self::TenantRestored => 'Tenant restored from archive',
            self::TenantDeleteAttempted => 'Tenant delete attempted',
            self::TenantDeleted => 'Tenant deleted',
            self::TenantUpdated => 'Tenant updated',
            self::UserEmailReleased => 'User email released',
            self::MembershipCreated => 'Membership created',
            self::MembershipRoleChanged => 'Membership role changed',
            self::MembershipStatusChanged => 'Membership status changed',
            self::MembershipRemoved => 'Membership removed',
            self::WidgetKeyCreated => 'Widget key created',
            self::WidgetKeyRotated => 'Widget key rotated',
            self::WidgetKeyRevoked => 'Widget key revoked',
            self::TenantDomainCreated => 'Tenant domain created',
            self::TenantDomainVerified => 'Tenant domain verified',
            self::TenantDomainRemoved => 'Tenant domain removed',
            self::ConfigurationUpdated => 'Configuration updated',
            self::BrandingUpdated => 'Branding updated',
            self::LogoUpdated => 'Logo updated',
            self::LogoRemoved => 'Logo removed',
            self::LauncherCardUpdated => 'Widget launcher card updated',
            self::LauncherCardImageUpdated => 'Widget launcher card image updated',
            self::LauncherCardImageRemoved => 'Widget launcher card image removed',
            self::OfficeHoursUpdated => 'Office hours updated',
            self::ServiceCreated => 'Service created',
            self::ServiceUpdated => 'Service updated',
            self::ServiceActivated => 'Service activated',
            self::ServiceDeactivated => 'Service deactivated',
            self::ServiceRemoved => 'Service removed',
            self::CourseCreated => 'Course created',
            self::CourseUpdated => 'Course updated',
            self::CourseActivated => 'Course activated',
            self::CourseDeactivated => 'Course deactivated',
            self::CourseRemoved => 'Course removed',
            self::InstitutionCreated => 'Institution created',
            self::InstitutionUpdated => 'Institution updated',
            self::InstitutionActivated => 'Institution activated',
            self::InstitutionDeactivated => 'Institution deactivated',
            self::InstitutionRemoved => 'Institution removed',
            self::LocationCreated => 'Location created',
            self::LocationUpdated => 'Location updated',
            self::LocationActivated => 'Location activated',
            self::LocationDeactivated => 'Location deactivated',
            self::LocationRemoved => 'Location removed',
            self::KnowledgeCreated => 'Knowledge created',
            self::KnowledgeUpdated => 'Knowledge updated',
            self::KnowledgePublished => 'Knowledge published',
            self::KnowledgeVersionCreated => 'Knowledge version created',
            self::KnowledgeArchived => 'Knowledge archived',
            self::KnowledgeDeleted => 'Knowledge deleted',
            self::KnowledgeSourceUploaded => 'Knowledge source uploaded',
            self::KnowledgeSourceRemoved => 'Knowledge source removed',
            self::FeeCreated => 'Fee created',
            self::FeeUpdated => 'Fee updated',
            self::FeeArchived => 'Fee archived',
            self::EligibilityCreated => 'Eligibility created',
            self::EligibilityUpdated => 'Eligibility updated',
            self::EligibilityArchived => 'Eligibility archived',
            self::CourseInstitutionCreated => 'Course institution created',
            self::CourseInstitutionUpdated => 'Course institution updated',
            self::AiConfigurationUpdated => 'AI configuration updated',
            self::AiSecretReplaced => 'AI secret replaced',
            self::PlatformSettingsUpdated => 'Platform settings updated',
            self::PlatformBypass => 'Platform bypass',
            self::LeadCreated => 'Lead created',
            self::LeadAssigned => 'Lead assigned',
            self::LeadReassigned => 'Lead reassigned',
            self::LeadStageChanged => 'Lead stage changed',
            self::LeadQualificationChanged => 'Lead qualification changed',
            self::LeadPriorityChanged => 'Lead priority changed',
            self::LeadFollowUpCreated => 'Lead follow-up created',
            self::LeadMarkedLost => 'Lead marked lost',
            self::LeadMarkedInvalid => 'Lead marked invalid',
            self::LeadConverted => 'Lead converted',
            self::LeadReopened => 'Lead reopened',
            self::LeadDeleted => 'Lead deleted',
            self::LeadRestored => 'Lead restored',
            self::LeadAdminOverride => 'Lead admin override',
            self::CounsellorCreated => 'Counsellor created',
            self::CounsellorUpdated => 'Counsellor updated',
            self::CounsellorActivated => 'Counsellor activated',
            self::CounsellorDeactivated => 'Counsellor deactivated',
            self::LeadQualificationRulesUpdated => 'Lead qualification rules updated',
            self::ConversationHandoffRequested => 'Conversation handoff requested',
            self::ConversationReassigned => 'Conversation reassigned',
            self::ConversationClosed => 'Conversation closed',
            self::ConversationReopened => 'Conversation reopened',
            self::ConversationAiResumed => 'Conversation AI resumed',
            self::PlanCreated => 'Plan created',
            self::PlanUpdated => 'Plan updated',
            self::PlanActivated => 'Plan activated',
            self::PlanDeactivated => 'Plan deactivated',
            self::SubscriptionAssigned => 'Subscription assigned',
            self::SubscriptionTrialStarted => 'Subscription trial started',
            self::SubscriptionTrialExtended => 'Subscription trial extended',
            self::SubscriptionActivated => 'Subscription activated',
            self::SubscriptionGraceApplied => 'Subscription grace applied',
            self::SubscriptionPastDue => 'Subscription past due',
            self::SubscriptionExpired => 'Subscription expired',
            self::SubscriptionCancelScheduled => 'Subscription cancellation scheduled',
            self::SubscriptionCancelled => 'Subscription cancelled',
            self::SubscriptionRestored => 'Subscription restored',
            self::SubscriptionPlanChanged => 'Subscription plan changed',
            self::PlanChangeRequested => 'Plan change requested',
            self::PlanChangeApproved => 'Plan change approved',
            self::PlanChangeRejected => 'Plan change rejected',
            self::EntitlementOverrideApplied => 'Entitlement override applied',
            self::EntitlementOverrideRemoved => 'Entitlement override removed',
            self::PlanPricingUpdated => 'Plan pricing updated',
            self::PaymentSecretReplaced => 'Payment secret replaced',
            self::PaymentSettingsUpdated => 'Payment settings updated',
            self::MessagingCredentialReplaced => 'Messaging credential replaced',
            self::MessagingIntegrationConfigured => 'Messaging integration configured',
            self::MessagingIntegrationEnabled => 'Messaging integration enabled',
            self::MessagingIntegrationDisabled => 'Messaging integration disabled',
        };
    }
}
